#############################################################################
# Makefile for building: final.app/Contents/MacOS/final
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  final.pro
# Template: app
# Command: /Users/annazhao/Qt/5.14.2/clang_64/bin/qmake -o Makefile final.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -D_USE_MATH_DEFINES -DTIXML_USE_STL -DGLM_SWIZZLE -DGLM_FORCE_RADIANS -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=c++14 -g -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.13 -Wextra -Waddress -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -fPIC $(DEFINES)
INCPATH       = -I. -Iglm -Iui -Iglew-1.10.0/include -I../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers -I../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.14.2/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.14.2/clang_64/lib/QtXml.framework/Headers -I../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../../Qt/5.14.2/clang_64/mkspecs/macx-clang -F/Users/annazhao/Qt/5.14.2/clang_64/lib
QMAKE         = /Users/annazhao/Qt/5.14.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/annazhao/Qt/5.14.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/annazhao/Qt/5.14.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = final1.0.0
DISTDIR = /Users/annazhao/Anna/brown/graphics/cabin-fever/.tmp/final1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/annazhao/Qt/5.14.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/annazhao/Qt/5.14.2/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtXml -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ui/mainwindow.cpp \
		main.cpp \
		glew-1.10.0/src/glew.c \
		ui/view.cpp \
		ui/viewformat.cpp \
		ui/Databinding.cpp \
		ui/Settings.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp \
		moc_Databinding.cpp
OBJECTS       = mainwindow.o \
		main.o \
		glew.o \
		view.o \
		viewformat.o \
		Databinding.o \
		Settings.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_view.o \
		moc_Databinding.o
DIST          = shaders/normals/normals.vert \
		shaders/normals/normals.frag \
		shaders/normals/normals.gsh \
		shaders/normals/normalsArrow.gsh \
		shaders/normals/normalsArrow.frag \
		shaders/normals/normalsArrow.vert \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/lex.prf \
		final.pro ui/mainwindow.h \
		ui_mainwindow.h \
		glew-1.10.0/include/GL/glew.h \
		ui/view.h \
		ui/viewformat.h \
		ui/Databinding.h \
		ui/Settings.h ui/mainwindow.cpp \
		main.cpp \
		glew-1.10.0/src/glew.c \
		ui/view.cpp \
		ui/viewformat.cpp \
		ui/Databinding.cpp \
		ui/Settings.cpp
QMAKE_TARGET  = final
DESTDIR       = 
TARGET        = final.app/Contents/MacOS/final

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/annazhao/Anna/brown/graphics/cabin-fever/final.pro


include /Users/annazhao/Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

final.app/Contents/MacOS/final: ui_mainwindow.h $(OBJECTS)  
	@test -d final.app/Contents/MacOS/ || mkdir -p final.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: final.pro ../../../../Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.14.2/clang_64/mkspecs/features/lex.prf \
		final.pro \
		resources.qrc \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../../Qt/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../../Qt/5.14.2/clang_64/lib/QtXml.framework/Resources/QtXml.prl \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile final.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../../../../Qt/5.14.2/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.14.2/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/toolchain.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/mac.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/resources_functions.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/qmake_use.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.14.2/clang_64/mkspecs/features/lex.prf:
final.pro:
resources.qrc:
../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../../Qt/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../../Qt/5.14.2/clang_64/lib/QtXml.framework/Resources/QtXml.prl:
../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile final.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

final.app/Contents/PkgInfo: 
	@test -d final.app/Contents || mkdir -p final.app/Contents
	@$(DEL_FILE) final.app/Contents/PkgInfo
	@echo "APPL????" > final.app/Contents/PkgInfo
final.app/Contents/Resources/empty.lproj: 
	@test -d final.app/Contents/Resources || mkdir -p final.app/Contents/Resources
	@touch final.app/Contents/Resources/empty.lproj
	
final.app/Contents/Info.plist: 
	@test -d final.app/Contents || mkdir -p final.app/Contents
	@$(DEL_FILE) final.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.final,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.final,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,final,g" -e "s,@LIBRARY@,final,g" -e "s,\$${EXECUTABLE_NAME},final,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../../Qt/5.14.2/clang_64/mkspecs/macx-clang/Info.plist.app >final.app/Contents/Info.plist

all: Makefile \
		final.app/Contents/PkgInfo \
		final.app/Contents/Resources/empty.lproj \
		final.app/Contents/Info.plist final.app/Contents/MacOS/final

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../Qt/5.14.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.h ui_mainwindow.h glew-1.10.0/include/GL/glew.h ui/view.h ui/viewformat.h ui/Databinding.h ui/Settings.h $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.cpp main.cpp glew-1.10.0/src/glew.c ui/view.cpp ui/viewformat.cpp ui/Databinding.cpp ui/Settings.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r final.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../../../Qt/5.14.2/clang_64/bin/rcc \
		shaders/shader.frag \
		shaders/shader.vert
	/Users/annazhao/Qt/5.14.2/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../Qt/5.14.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -std=c++14 -g -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.13 -Wextra -Waddress -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -dM -E -o moc_predefs.h ../../../../Qt/5.14.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp moc_Databinding.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp moc_Databinding.cpp
moc_mainwindow.cpp: ui/mainwindow.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../../../../Qt/5.14.2/clang_64/bin/moc
	/Users/annazhao/Qt/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/annazhao/Anna/brown/graphics/cabin-fever/moc_predefs.h -I/Users/annazhao/Qt/5.14.2/clang_64/mkspecs/macx-clang -I/Users/annazhao/Anna/brown/graphics/cabin-fever -I/Users/annazhao/Anna/brown/graphics/cabin-fever/glm -I/Users/annazhao/Anna/brown/graphics/cabin-fever/ui -I/Users/annazhao/Anna/brown/graphics/cabin-fever/glew-1.10.0/include -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtXml.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/annazhao/Qt/5.14.2/clang_64/lib ui/mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: ui/view.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		../../../../Qt/5.14.2/clang_64/bin/moc
	/Users/annazhao/Qt/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/annazhao/Anna/brown/graphics/cabin-fever/moc_predefs.h -I/Users/annazhao/Qt/5.14.2/clang_64/mkspecs/macx-clang -I/Users/annazhao/Anna/brown/graphics/cabin-fever -I/Users/annazhao/Anna/brown/graphics/cabin-fever/glm -I/Users/annazhao/Anna/brown/graphics/cabin-fever/ui -I/Users/annazhao/Anna/brown/graphics/cabin-fever/glew-1.10.0/include -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtXml.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/annazhao/Qt/5.14.2/clang_64/lib ui/view.h -o moc_view.cpp

moc_Databinding.cpp: ui/Databinding.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QButtonGroup \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDockWidget \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDial \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		moc_predefs.h \
		../../../../Qt/5.14.2/clang_64/bin/moc
	/Users/annazhao/Qt/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/annazhao/Anna/brown/graphics/cabin-fever/moc_predefs.h -I/Users/annazhao/Qt/5.14.2/clang_64/mkspecs/macx-clang -I/Users/annazhao/Anna/brown/graphics/cabin-fever -I/Users/annazhao/Anna/brown/graphics/cabin-fever/glm -I/Users/annazhao/Anna/brown/graphics/cabin-fever/ui -I/Users/annazhao/Anna/brown/graphics/cabin-fever/glew-1.10.0/include -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtXml.framework/Headers -I/Users/annazhao/Qt/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/annazhao/Qt/5.14.2/clang_64/lib ui/Databinding.h -o moc_Databinding.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui/mainwindow.ui \
		../../../../Qt/5.14.2/clang_64/bin/uic \
		ui/view.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qtimer.h
	/Users/annazhao/Qt/5.14.2/clang_64/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: ui/mainwindow.cpp ui/mainwindow.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		ui/view.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/QGLFormat \
		ui/Databinding.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QButtonGroup \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDockWidget \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDial \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		ui/Settings.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ui/mainwindow.cpp

main.o: main.cpp ../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		ui/mainwindow.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

glew.o: glew-1.10.0/src/glew.c glew-1.10.0/include/GL/glew.h \
		glew-1.10.0/include/GL/wglew.h \
		glew-1.10.0/include/GL/glxew.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glew.o glew-1.10.0/src/glew.c

view.o: ui/view.cpp ui/view.h \
		glew-1.10.0/include/GL/glew.h \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		ui/viewformat.h \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/QGLFormat \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../../Qt/5.14.2/clang_64/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o ui/view.cpp

viewformat.o: ui/viewformat.cpp ui/viewformat.h \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/QGLFormat \
		../../../../Qt/5.14.2/clang_64/lib/QtOpenGL.framework/Headers/qgl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewformat.o ui/viewformat.cpp

Databinding.o: ui/Databinding.cpp ui/Databinding.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QButtonGroup \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDockWidget \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDial \
		../../../../Qt/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Databinding.o ui/Databinding.cpp

Settings.o: ui/Settings.cpp ui/Settings.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../../Qt/5.14.2/clang_64/lib/QtCore.framework/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings.o ui/Settings.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_Databinding.o: moc_Databinding.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Databinding.o moc_Databinding.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

